<?php $otp = $this->getRequest()->getParam('OTP'); if(!$otp) {?>
<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information for OTP verification') ?></span></legend>
    <p>
    <div class="field regulation">
        <label for="regulation" class="label"><span><?php /* @escapeNotVerified */
                echo __('Customer Mobile') ?></span></label>
        <div class="control">
            <input type="text" name="customer_mobile" id="customer_mobile" title="<?php /* @escapeNotVerified */ echo __('Customer Mobile') ?>" class="input-text" data-validate="{required:false}">
        </div>
    </div>
    </p>
</fieldset>
<?php }else{ ?>
<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information for OTP verification') ?></span></legend>
    <p>
    <div class="field regulation">
        <label for="regulation" class="label"><span><?php /* @escapeNotVerified */
                echo __('Enter OTP') ?></span></label>
        <div class="control">
            <input type="text" name="mobile_otp" id="mobile_otp" title="<?php /* @escapeNotVerified */ echo __('OTP') ?>" class="input-text" data-validate="{required:true}">
            <input type="hidden" name="verify_otp" id="verify_otp" value="<?php echo $otp; ?>" class="input-text" data-validate="{required:false}">
            <input type="hidden" name="customer_mobile" id="customer_mobile" value="<?php echo $this->getRequest()->getParam('customer_mobile'); ?>" class="input-text" data-validate="{required:false}">
            <input type="hidden" name="otp_counter" id="otp_counter" value="<?php echo $this->getRequest()->getParam('otp_counter'); ?>" class="input-text" data-validate="{required:false}">
            <input type="hidden" name="created_at" id="created_at" value="<?php echo $this->getRequest()->getParam('created_at'); ?>" class="input-text" data-validate="{required:false}">
        </div>
    </div>
    </p>
</fieldset>
<?php } ?>
